source "https://rubygems.org"

# Bundle edge Rails instead: gem "rails", github: "rails/rails"
gem "rails", "4.0.1"

# Use Postgres as the database for Active Record
gem "pg"

# Auth
gem "devise"

#Fake stuffs
gem "faker"

#pagination
gem "kaminari"

# App tracking
gem "skylight"

# Settings
gem "rails_config"

gem "active_model_serializers"

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem "sdoc", require: false
end

group :development do
  gem "better_errors"
  gem "binding_of_caller"
end
